name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Run build script
        run: |
          ./build.bat

      - name: copy new JAR files
        run: |
          copy jar\custom_spider.jar jar\update.jar   

      - name: Commit JAR files to target repository
        run: |
          # 克隆目标仓库
          git clone https://${{ secrets.DAV_SECRET}}@github.com/david0501z/davstore.git target-repo
          cd target-repo

          # 复制生成的 JAR 文件到目标仓库
          cp -r ../jar/update.jar ./jar/

          # 配置 Git 用户信息
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'

          # 提交并推送更改
          git add jar/
          git commit -m 'Update generated JAR files'
          git push origin main
        env:
          # 使用 PAT 进行认证
          GITHUB_TOKEN: ${{ secrets.DAV_SECRET }}
