name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Run build script
        run: |
          ./build.bat

      - name: copy new JAR files
        run: |
          copy jar\custom_spider.jar jar\update.jar
          

      - name: Commit JAR files
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add jar/custom_spider.jar jar/custom_spider.jar.md5 jar/update.jar
          git commit -m 'Update generated custom_spider.jar and custom_spider.jar.md5  jar/update.jar'
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
